steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-east2-docker.pkg.dev/praxis-dolphin-333916/telebot/telebot-image:$COMMIT_SHA'
      - '-t'
      - 'asia-east2-docker.pkg.dev/praxis-dolphin-333916/telebot/telebot-image:latest'
      - '--cache-from'
      - 'asia-east2-docker.pkg.dev/praxis-dolphin-333916/telebot/telebot-image:latest'
      - '.'
    id: 'build'

  # Step 2: Push the Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-east2-docker.pkg.dev/praxis-dolphin-333916/telebot/telebot-image:$COMMIT_SHA'
    id: 'push'

  # Step 3: Verify SSH connection to the new instance with retry mechanism
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'sshtesting'
      - '--zone=asia-east2-a'
      - '--command=echo "SSH works!"'
      - '--retry-on-failure'
    id: 'verify-ssh'

  # Step 4: Verify and install Docker on GCE instance if not present
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'verify-and-install-docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if ! gcloud compute ssh sshtesting --zone asia-east2-a --command 'command -v docker'; then
          gcloud compute ssh sshtesting --zone asia-east2-a --command 'sudo apt-get update && sudo apt-get install -y docker.io'
        fi
    waitFor: ['verify-ssh']

  # Step 5: Pull the Docker image from Google Artifact Registry onto the instance
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'pull-image'
    args:
      - 'compute'
      - 'ssh'
      - 'sshtesting'
      - '--zone'
      - 'asia-east2-a'
      - '--command'
      - 'docker pull asia-east2-docker.pkg.dev/praxis-dolphin-333916/telebot/telebot-image:latest'

  # Step 6: Run the Docker container
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'run-container'
    args:
      - 'compute'
      - 'ssh'
      - 'sshtesting'
      - '--zone'
      - 'asia-east2-a'
      - '--command'
      - |
          docker stop telebot-container || true &&
          docker rm telebot-container || true &&
          docker run -d --name telebot-container -p 80:80 asia-east2-docker.pkg.dev/praxis-dolphin-333916/telebot/telebot-image:latest

images:
  - 'asia-east2-docker.pkg.dev/praxis-dolphin-333916/telebot/telebot-image:latest'

options:
  logging: CLOUD_LOGGING_ONLY
timeout: '1200s'